# condor commands
# Set the accounting tag from https://ldas-gridmon.ligo.caltech.edu/ldg_accounting/user
ACCOUNTING_TAG=ligo.prod.o1.cbc.bbh.gstlaloffline
GROUP_USER=duncan.meacher
CONDOR_COMMANDS:=--condor-command=accounting_group=$(ACCOUNTING_TAG) --condor-command=accounting_group_user=$(GROUP_USER) --condor-command='Requirements=TARGET.cpuinfo_model=?="60"'

#
# Triggering parameters
#

# The detectors to analyze
IFOS = H1 L1 
# The GPS start time for analysis3 (O1C)
START = 1129383017
# The GPS end time for analysis3 (O1C)
STOP = 1133173817
# A user tag for the run
TAG = vt_sensitivity_runs
# A web directory for output
WEBDIR = ~/WWW/LSC/MDC/VT_sensitivity/$(TAG)/$(START)-$(STOP)-chunk456-NSBH-C02-run1
# The number of sub banks to process in parallel for each gstlal_inspiral job
NUMBANKS = 5
# The control peak time for the composite detection statistic.  If set to 0 the
# statistic is disabled
PEAK = 0
# The length of autocorrelation chi-squared in sample points
AC_LENGTH = 351
# The minimum number of samples to include in a given time slice
SAMPLES_MIN = 512
# The maximum number of samples to include in the 256 Hz or above time slices
SAMPLES_MAX_256 = 512

#
# Injections
#

# The seed is the string before the suffix _injections.xml
# Change as appropriate, whitespace is important
# This injection file obtained from /home/gstlalcbc/observing/1/offline/er8b-test/HL-INJECTIONS_78901_BBH1-1123858817-3661199.xml
INJECTIONS := U_dVdzo1pz_nsbh05_aligned_injections_v1.xml.gz U_dVdzo1pz_nsbh05_isotropic_injections_v3.xml.gz U_dVdzo1pz_nsbh10_aligned_injections_v1.xml.gz U_dVdzo1pz_nsbh10_isotropic_injections_v3.xml.gz U_dVdzo1pz_nsbh30_aligned_injections_v1.xml.gz U_dVdzo1pz_nsbh30_isotropic_injections_v3.xml.gz

# The Channel names. FIXME sadly you have to change the CHANNEL_NAMES string if
# you want to analyze a different set of IFOS
H1_CHANNEL=DCS-CALIB_STRAIN_C02
L1_CHANNEL=DCS-CALIB_STRAIN_C02
CHANNEL_NAMES:=--channel-name=H1=$(H1_CHANNEL) --channel-name=L1=$(L1_CHANNEL)

# Set to original run directory and and zero lag database.
# Zero lag run
ZERO_LAG_DIR:=/home/gstlalcbc/MDC/vt_sensitivity/O1_rate_injection_runs/1129383017-1133173817-chunk456-BBH-C02-run1
ZERO_LAG_DB:=$(ZERO_LAG_DIR)/H1L1-ALL_LLOID-1129383017-3790800.sqlite

# These shouldn't need to be changed.
PRIOR_CACHE:=$(ZERO_LAG_DIR)/prior.cache
SVD_CACHE:=$(ZERO_LAG_DIR)/svd_bank.cache
PSD_CACHE:=$(ZERO_LAG_DIR)/psd.cache
DIST_STATS_CACHE:=$(ZERO_LAG_DIR)/dist_stats.cache
SEGMENTS:=$(ZERO_LAG_DIR)/segments.xml.gz
VETOES:=$(ZERO_LAG_DIR)/vetoes.xml.gz
FRAME_CACHE:=$(ZERO_LAG_DIR)/frame.cache
TISI:=$(ZERO_LAG_DIR)/tisi.xml
H1_BANK_CACHE:=$(ZERO_LAG_DIR)/H1_split_bank.cache
L1_BANK_CACHE:=$(ZERO_LAG_DIR)/L1_split_bank.cache
PSD_CACHE:=$(ZERO_LAG_DIR)/psd.cache
MARG:=$(ZERO_LAG_DIR)/marginalized_likelihood.xml.gz
POSTMARG:=$(ZERO_LAG_DIR)/post_marginalized_likelihood.xml.gz
BANK_CACHE_FILES:=$(H1_BANK_CACHE) $(L1_BANK_CACHE)

#
# Get some basic definitions.  NOTE this comes from the share directory probably.
#

include Makefile.offline_analysis_rules

#
# Workflow
#

all : dag

plots :
	mkdir plots

$(WEBDIR) : $(MAKEFILE_LIST)
	mkdir -p $(WEBDIR)/OPEN-BOX

dag : $(PRIOR_CACHE) $(SVD_CACHE) $(DIST_STATS_CACHE) $(ZERO_LAG_DB) $(SEGMENTS) $(VETOES) $(FRAME_CACHE) $(TISI) plots $(WEBDIR) $(INJECTIONS) $(L1_BANK_CACHE) $(H1_BANK_CACHE) $(PSD_CACHE) $(MARG)
	cp $(H1_BANK_CACHE) .
	cp $(L1_BANK_CACHE) .
	cp $(MARG) .
	cp $(POSTMARG) .
	/home/gstlalcbc/local/src/gstlal/gstlal-inspiral/bin/gstlal_inspiral_inj_pipe --data-source frames --gps-start-time $(START) --gps-end-time $(STOP) --frame-cache $(FRAME_CACHE) --frame-segments-file $(SEGMENTS) --vetoes $(VETOES) --frame-segments-name datasegments  --control-peak-time $(PEAK) --fir-stride 1 --web-dir $(WEBDIR) --time-slide-file $(TISI) $(INJECTION_LIST) $(CHANNEL_NAMES) --ht-gate-threshold 50 $(CONDOR_COMMANDS) --singles-threshold 6.0 --prior-cache $(PRIOR_CACHE) --svd-bank-cache $(SVD_CACHE) --dist-stats-cache $(DIST_STATS_CACHE) --non-injection-db $(ZERO_LAG_DB) --bank-cache $(BANK_CACHE_STRING) --psd-cache $(PSD_CACHE) --marginalized-likelihood-file marginalized_likelihood.xml.gz --request-cpu 4 --request-memory 7GB
	sed -i '1s/^/JOBSTATE_LOG logs\/trigger_pipe.jobstate.log\n/' trigger_pipe.dag

clean:
	-rm -rvf *.sub *.dag* *.cache *.sh logs *.sqlite plots *.html Images *.css *.js
	-rm -rvf lalapps_run_sqlite/ ligolw_* gstlal_*
	-rm -vf segments.xml.gz tisi.xml H1-*.xml H1_*.xml L1-*.xml L1_*xml V1-*.xml V1_*xml ?_injections.xml ????-*_split_bank-*.xml vetoes.xml.gz
	-rm -vf *marginalized*.xml.gz *-ALL_LLOID*.xml.gz
	-rm -vf tisi0.xml tisi1.xml
	-rm -rf *_split_bank*
	-rm -rf nogaps.xml segdb.xml
	-rm -rf bank_aligned_spin.xml.gz
