image: ligo/software:stretch

variables:
  DOCKER_DRIVER: overlay
  BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  NIGHTLY: $CI_REGISTRY_IMAGE:nightly
  TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  GSTLAL_DIR: $CI_PROJECT_DIR/opt/gstlal

before_script:
    - export PATH="${GSTLAL_DIR}/bin:${PATH}"
    - export PKG_CONFIG_PATH="${GSTLAL_DIR}/lib/pkgconfig:${GSTLAL_DIR}/lib64/pkgconfig:${PKG_CONFIG_PATH}"
    - export GI_TYPELIB_PATH="${GSTLAL_DIR}/lib/girepository-1.0:${GI_TYPELIB_PATH}"
    - export GST_PLUGIN_PATH="/opt/gstlal/lib/gstreamer-1.0:${GST_PLUGIN_PATH}"
    - export PYTHONPATH="${GSTLAL_DIR}/lib64/python2.7/site-packages:${GSTLAL_DIR}/lib/python2.7/site-packages:${PYTHONPATH}"
    - export GSTLAL_FIR_WHITEN=1

stages:
    - nightly-pages

pages:
  #Build from the nightly lalsuite container:
  image: containers.ligo.org/lscsoft/lalsuite:nightly
  stage: nightly-pages
  script:
    - mkdir public
    - echo "Building GstLAL"
    - apt update
    # Pull installation dependencies:
    - apt-get --assume-yes install automake graphviz texlive-full
    # Pull GstLAL-specific dependencies:
    - apt-get --assume-yes install doxygen gtk-doc-tools libfftw3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev liborc-0.4-0 gobject-introspection python-gobject-dev python-numpy python-scipy lscsoft-gds
    - cd gstlal; ./00init.sh; ./configure --prefix=${GSTLAL_DIR}; make; make install
    - cd ../gstlal-ugly; ./00init.sh; ./configure --prefix=${GSTLAL_DIR}; make; make install
    - cd ../gstlal-calibration; ./00init.sh; ./configure --prefix=${GSTLAL_DIR}; make; make install
    - cd ../gstlal-inspiral; ./00init.sh; ./configure --prefix=${GSTLAL_DIR}; make; make install
    - echo "Building Documentation"
    - apt-get --assume-yes install python-sphinx
    - export TMPDIR=tmp/
    - cd ../doc; make html
    - cd ..; cp -rf doc/_build/* public/
    
  dependencies: []
  artifacts:
    paths:
      - public
  only:
    - master@alexander-pace/gstlal
    - pushes
  except:
    - web