#!/usr/bin/python

import numpy
import sys
from gstlal import reference_psd
from pylal.xlal import datatypes
from pylal.xlal.datatypes import lalunit

det = sys.argv[1]
file = sys.argv[2]

data = numpy.loadtxt(file)
f = data[:,0]
psd = data[:,1]**2
df = f[2] - f[1]

#FIXME hack to pad the series since it doesn't start at 0 :(
fstart = f[0]
psd = numpy.concatenate((numpy.ones(fstart / df) * psd[0],psd))

psdseries = datatypes.real8frequencyseries.REAL8FrequencySeries(deltaF=df, data=psd, sampleUnits=lalunit.LALUnit("s strain^2"), f0=0)
reference_psd.write_psd(file.replace(".txt",".xml.gz"), {None: psdseries})

