all: DCS_over_C02

DCS_over_C02: $(IFO)1_hoft_DCS_frames.cache $(IFO)1_C02_frames.cache
	python ../../check_calibration/plot_transfer_function.py --gps-start-time $(SHORT_PLOT_START) --gps-end-time $(SHORT_PLOT_END) --ifo $(IFO)1 --numerator-frame-cache-list $(IFO)1_hoft_DCS_frames.cache --denominator-frame-cache $(IFO)1_C02_frames.cache --numerator-channel-list DCS-CALIB_STRAIN --denominator-channel-name DCS-CALIB_STRAIN_C02 --denominator-name 'C02' --numerator-name 'DCS_TEST --magnitude-min 0.7 --magnitude-max 1.3 --phase-min -20.0 --phase-max 20.0 --labels 'DCS Test / C02 Transfer Function'

clean:
	*.png

