# time of GW170817 1187008882
#SHELL=/bin/bash
START = 1187007882 # Thu Aug 17 12:24:24 GMT 2017
END = 1187008582 # Thu Aug 17 12:36:04 GMT 2017
PLOT_START = $(shell echo $(START) + 200 | bc)
PLOT_END = $(shell echo $(END) - 100 | bc)
#PLOTSTART = 1187008082
#PLOTEND = 1187008482
FILTER = 'L1DCS_1175961600.npz'
IFO = L
#Note: Make sure there is no space after the L or H

all: Filter_for_Frames DCS_CALCS_plots

Filter_for_Frames: 
	cp Filters/GDSFilters/$(FILTER) Frames/DCS_calibration

raw_frames.cache: 
	cd Frames/DCS_calibration; gw_data_find -o $(IFO) -t $(IFO)1_R -s $(START) -e $(END) -l --url-type file > $@

hoft_frames.cache: raw_frames.cache
	cd Frames/DCS_calibration; gstlal_compute_strain --data-source frames --frame-cache raw_frames.cache --gps-start-time $(START) --gps-end-time $(END) --frame-duration=4 --frames-per-file=1 --filters-file $(FILTER) --ifo $(IFO)1 --frame-type $(IFO)1_TEST --compression-scheme=6 --compression-level=3 --full-calibration --control-sample-rate 16384 --factors-from-filters-file --expected-fcc 376.0 --no-fs --no-srcQ --coherence-uncertainty-threshold 0.02 --kappas-default-to-median --apply-kappatst --apply-kappapu --apply-kappac --verbose
	cd Frames/DCS_calibration; ls *.gwf | lalapps_path2cache > $@

DCS_CALCS_plots: raw_frames.cache hoft_frames.cache
	./ASD_comparison_plots --ifo $(IFO)1 --gps-start-time $(PLOT_START) --gps-end-time $(PLOT_END) --raw-frame-cache Frames/DCS_calibration/raw_frames.cache --gds-frame-cache Frames/DCS_calibration/hoft_frames.cache 


clean: 
	cd Frames/DCS_calibration; rm *.cache *.gwf 
	rm *.png 

