# This makefile can be used to run all of the tests instead of running them one by one.

all: response_function DCS_calibration timeserieskappas

response_function:
	make -f Makefile.response_function

DCS_calibration: 
	make -f Makefile.DCS_calibration

timeserieskappas:
	make -f Makefile.timeserieskappas

clean: 
	rm *.pdf
	cd Frames/response_function/C00_no_kappas; rm *.gwf *.cache
	cd Frames/response_function/C01_no_kappas; rm *.gwf *.cache  
	rm *.png
	cd Frames/DCS_calibration; rm *.gwf *.cache

