all: ASD_comparison_plots

ASD_comparison_plots: 
	python ../../check_calibration/ASD_comparison_plots --ifo $(IFO)1 --gps-start-time $(SHORT_PLOT_START) --gps-end-time $(SHORT_PLOT_END) --raw-frame-cache $(IFO)1_raw_frames.cache --hoft-frame-cache $(IFO)1_hoft_DCS_frames.cache --calcs-channel-name CAL-DELTAL_EXTERNAL_DQ --additional-hoft-frame-cache $(IFO)1_C00_frames.cache --analyze-additional-hoft-channel --additional-hoft-channel-name GDS-CALIB_STRAIN --hoft-channel-name DCS-CALIB_STRAIN

clean: 
	rm *.png 

