#!/usr/bin/python
import sys
import cgi
import cgitb
import os
os.environ["MPLCONFIGDIR"] = "/tmp"
import matplotlib
matplotlib.use('Agg')
import numpy
# FIXME don't import this when it is "real"
from numpy import random
import matplotlib.pyplot as plt
import time
cgitb.enable()
form = cgi.FieldStorage()

def now():
	#FIXME use pylal when available
	return time.time() - 315964785

def read_registry(dir, dataurl, idrange):
	nodedict = {}
	ids = ['%04d' % (job,) for job in range(idrange[0], idrange[1]+1)]
	for id in ids:
		url = '%s/%s%s' % (dir, id, dataurl)
		# FIXME relies on 4 digit id
		try:
			tmp = open(url,"r")
			tag, node = tmp.readline().split()
			tmp.close()
			nodedict[id] = node
		except IOError:
			nodedict[id] = ""
	return nodedict
	

def plot(dir, dataurl, idrange, registry, plottype = "value", datatype = "last", xlabel = "", ylabel = "", title = ""):
	fig = plt.figure(figsize=(25,6.5),)
	fig.patch.set_alpha(0.0)
	h = fig.add_subplot(111, axisbg = 'k')
	plt.subplots_adjust(left = .03, right = 0.98, bottom = 0.3)

	data = []
	timestamp = []
	ids = ['%04d' % (job,) for job in range(idrange[0], idrange[1]+1)]

	for id in ids:
		url = '%s/%s%s' % (dir, id, dataurl)
		# FIXME relies on 4 digit id
		try:
			tmp = numpy.loadtxt(url)
			if datatype == "last":
				data.append(tmp[-1,1])
			if datatype == "max":
				data.append(tmp[:,1].max())
			timestamp.append(now() - tmp[-1,0] )
		except IOError:
			data.append(-1)
			timestamp.append(-1)

	def process(plotdata):
		# first plot the missing data
		data = numpy.array(plotdata)
		maxdata = data.max()
		x = [i for i,d in enumerate(data) if d == -1]
		badvalue = -0.05 * maxdata
		baddata = [badvalue for d in data if d == -1]
		h.bar(x, baddata, color='r', alpha=0.9, linewidth=2)
		# then the regular data
		data[data ==  -1] = 0
		x = numpy.arange(len(data))
		h.bar(x, data, color='w', alpha=0.75, linewidth=2)
		ticks = ["%s : %s " % (id, registry[id]) for id in ids]
		plt.xticks(x+.3, ticks, rotation=90)
		plt.ylabel(ylabel, fontsize = 18)
		plt.ylim([badvalue, maxdata])
		plt.xlim([x[0], x[-1]+1])
		if title:
			plt.title(title, fontsize=18)
		plt.savefig(sys.stdout, format="svg")
	
	if plottype == "value":
		process(data)
	if plottype == "timestamp":
		process(timestamp)


if "dir" not in form:
	raise ValueError("must specify dir")
if "id" not in form:
	raise ValueError("must specify id")

idrange = [int(n) for n in form.getvalue("id").split(",")]
reg = read_registry(form.getvalue("dir"), "_registry.txt", idrange)

print >>sys.stdout, 'Cache-Control: no-cache, must-revalidate'
print >>sys.stdout, 'Expires: Mon, 26 Jul 1997 05:00:00 GMT'
print >>sys.stdout, 'Content-type: text/html\r\n'

print """
<html>
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
</head>
<body bgcolor=#E0E0E0 face="Arial">
"""
print "<center><h1>Low-latency Compact Binary Online (LCBO) summary: %d - %s </h1></center><br>" % (int(now()), time.strftime("%a, %d %b %Y %H:%M:%S", time.localtime()))
"""
<table>
<tr>
<td><div id='canvasa'>
"""
plot(form.getvalue("dir"), '_latency_history.txt', idrange, reg, ylabel = "Latency (s)", title = "Latency summary of all jobs, red means data is missing")
print """
</div></td></tr>
<tr><td><div id='canvasb'>
"""
plot(form.getvalue("dir"), '_ram_history.txt', idrange, reg, ylabel = "RAM (GB)", title = "RAM summary of all jobs, red means data is missing")
print """
</div></td></tr>
<tr><td><div id='canvasc'>
"""
plot(form.getvalue("dir"), '_snr_history.txt', idrange, reg, datatype = "max", ylabel = "SNR", title = "max(SNR) of recent triggers summary of all jobs, red means data is missing")
print """
</div></td></tr>
<tr><td><div id='canvasd'>
"""
plot(form.getvalue("dir"), '_snr_history.txt', idrange, reg, plottype = "timestamp", ylabel = "Time (s)", xlabel = "Time before now (s)", title = "Time since last update (s), red means data is missing")
print """
</div></td>
</tr>
</table>
"""
for k in range(idrange[0], idrange[1]+1):
	print '<a href="llcbcnode?dir=%s&id=%04d">%04d</a>' % (form.getvalue("dir"), k, k)
print """
</body>
"""

