#!/usr/bin/python

import os,sys
import cgi
import cgitb
cgitb.enable()
form = cgi.parse()
import time

if "GPS" in form:
	gps = form["GPS"][0]
else:
	gps = "-1"

if gps == "-1":
	refresh = 5
	longrefresh = 60
else:
	refresh =     0
	longrefresh = 0

if "Duration" in form:
	duration = form["Duration"][0]
else:
	duration = "600"

if "dir" in form:
	analysis_path = form["dir"][0]
else:
	analysis_path = "/home/gstlalcbctest/engineering/10/S6/bns"

if "id" in form:
	job_ids = form["id"][0]
else:
	job_ids = "0000,0009"
	
		
print "Content-type: text/html"
print "Cache-Control: max-age=10"
print

print '''
<html>
<head>
	<title>gstlal CBC Latency</title>
	<link rel="stylesheet" type="text/css" href="../gstlal.css">
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script type="text/javascript" src="../jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="../gstlal.js"></script>
	<script type="text/javascript">
	google.charts.load('current', {'packages':['corechart', 'table']});
'''

print "	google.charts.setOnLoadCallback(function(){ drawLatencyStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawLatencyHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawLatencyGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print ""
print "	google.charts.setOnLoadCallback(function(){ drawSNRStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawSNRHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawLikelihoodStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawLikelihoodHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawFARStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawFARHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print ""
print "	google.charts.setOnLoadCallback(function(){ drawHorizon(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawNoise(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawPSD(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawNoiseGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawRangeGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawUpTime(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawUpTimeGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawDroppedData(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawRAMStatus(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawTimeSinceLast(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)

print '''
	</script>
</head>

<body>
	<form>
	<!-- <div class=topbox> -->
		<ul class="tab">
			<li><img style="width: 100px; margin: 5px 5px 5px 5px;" src="http://www.lsc-group.phys.uwm.edu/cgit/gstlal/plain/gstlal/doc/gstlal.png"></li>
			<!-- <li><a href="#ldg" class="tablinks" onclick="openGstlalTab(event, 'LDG')">LDG</a></li> -->
			<!-- <li><a href="#dashboard" class="tablinks" onclick="openGstlalTab(event, 'Dashboard')">Dashboard</a></li>-->
			<!-- <li><a href="#events" class="tablinks" onclick="openGstlalTab(event, 'Events')">Events</a></li> -->
			<li><a href="#summary" class="tablinks" onclick="openGstlalTab(event, 'Summary')">Results</a></li>
			<li><a href="#status" class="tablinks" onclick="openGstlalTab(event, 'Status', time_since_last_wrapper, up_time_wrapper, dropped_wrapper, ram_status_wrapper)">Live Status</a></li>
			<li><a href="#sens" class="tablinks" onclick="openGstlalTab(event, 'Sensitivity', horizon_wrapper, psd_wrapper)">Live Sensitivity</a></li>
			<li><a href="#noise" class="tablinks" onclick="openGstlalTab(event, 'Noise', noise_wrapper)">Live Noise</a></li>
			<li><a href="#latency" class="tablinks" onclick="openGstlalTab(event, 'Latency', latency_status_by_nodes_wrapper, latency_history_wrapper)">Live Latency</a></li>
			<li><a href="#snr" class="tablinks" onclick="openGstlalTab(event, 'SNR', snr_status_by_nodes_wrapper, snr_history_wrapper, likelihood_status_by_nodes_wrapper, likelihood_history_wrapper, far_status_by_nodes_wrapper, far_history_wrapper)">Live SNR</a></li>
			<li><a href="#detchar" class="tablinks" onclick="openGstlalTab(event, 'Detchar')">Detchar</a></li>
			<li><a href="#logs" class="tablinks" onclick="openGstlalTab(event, 'Logs')">Logs</a></li>
			<li>
'''				
print '			<input type="text" name="GPS" value="%s" size=8 style="margin: 7px 5px 5px 5px;"><input type="submit" value="GPS" style="margin: 7px 5px 5px 5px;">' % (gps,)
print '			<input type="text" name="Duration" value="%s" size=4 style="margin: 7px 5px 5px 5px;">' % (duration,)
print '			<input type="submit" value="Duration" style="margin: 7px 5px 5px 5px;">'
print '''			
			</li>
			<div id="clock" style="text-align: right; margin: 7px 5px 5px 5px;"></div>
		</ul>
	<!-- </div> -->
	</form>

	<!--
	<div id="LDG" class="tabcontent">
		<iframe src="https://monitor.ligo.org/gwstatus" width=100% height=675></iframe>
	</div>
	-->

	<div id="Dashboard" class="tabcontent">
		<div id="range_gauge_wrapper"></div>
		<div id="noise_gauge_wrapper"></div>
		<table><tr>	<td><div id="uptime_gauge_wrapper"></div></td>
				<td><div id="latency_gauge_wrapper"></div></td>
		</tr></table>
	</div>

	<div id="Logs" class="tabcontent">
		<table width=100%>
			<tr><td><iframe src="https://alog.ligo-wa.caltech.edu/aLOG/iframeSrc.php?authExpired=&content=1&step=&callRep=&startPage=&preview=&printCall=&callUser=&addCommentTo=&callHelp=&callFileType=#&reportSection=8&reportTask=General" width=100% height=675></iframe></td>
			<td><iframe src="https://alog.ligo-la.caltech.edu/aLOG/iframeSrc.php?authExpired=&content=1&step=&callRep=&startPage=&preview=&printCall=&callUser=&addCommentTo=&callHelp=&callFileType=#&reportSection=6&reportTask=General" width=100% height=675></iframe></td></tr>
		</table>
	</div>

	<div id="Detchar" class="tabcontent">
'''

if gps =="-1":
	print '''		<iframe src="https://ldas-jobs.ligo.caltech.edu/~detchar/summary/" width=100% height=675></iframe>'''
else: 
	date = "%04d%02d%02d" % time.gmtime(int(gps)+ 315964785)[0:3]
	print '''		<iframe src="https://ldas-jobs.ligo.caltech.edu/~detchar/summary/day/%s/" width=100%% height=675></iframe>''' % (date,)

print '''
	</div>

	<!--
	<div id="Events" class="tabcontent">
		<iframe src="https://gracedb.ligo.org/latest/?query=gstlal" width=100% height=675></iframe>
	</div>
	-->

	<div id="Noise" class="tabcontent">
		<div id="noise_wrapper"></div>
		<div id="noise_table_wrapper"></div>
	</div>

	<div id="Sensitivity" class="tabcontent">
		<div id="horizon_wrapper"></div>
		<div id="psd_wrapper"></div>
		<div id="horizon_table_wrapper"></div>
	</div>

	<div id="Latency" class="tabcontent">
		<div id="latency_status_by_nodes_wrapper"></div>
		<div id="latency_history_wrapper"></div>
	</div>

	<div id="SNR" class="tabcontent">
		<div id="snr_status_by_nodes_wrapper"></div>
		<div id="snr_history_wrapper"></div>
		<div id="likelihood_status_by_nodes_wrapper"></div>
		<div id="likelihood_history_wrapper"></div>
		<div id="far_status_by_nodes_wrapper"></div>
		<div id="far_history_wrapper"></div>
	</div>

	<div id="Status" class="tabcontent">
		<div id="time_since_last_wrapper"></div>
		<div id="up_time_wrapper"></div>
		<div id="dropped_wrapper"></div>
		<div id="ram_status_wrapper"></div>
	</div>
	<div id="Summary" class="tabcontent">
		<iframe src="https://ldas-jobs.ligo.caltech.edu/~gstlalcbctest/engineering/10/" width=100% height=675></iframe>
	</div>
</body>
</html>
'''
