#!/usr/bin/python

import os,sys
import cgi
import cgitb
cgitb.enable()
form = cgi.parse()
import time

if "GPS" in form:
	gps = form["GPS"][0]
	if float(gps) > 0:
		refresh =     0
		longrefresh = 0
	else:
		refresh =     5
		longrefresh = 30
else:
	gps = "-1"
	refresh =     5
	longrefresh = 30


if "Duration" in form:
	duration = form["Duration"][0]
else:
	duration = "3600"

if "dir" in form:
	analysis_path = form["dir"][0]
else:
	analysis_path = "/home/gstlalcbctest/engineering/10/S6/bns"

if "id" in form:
	job_ids = form["id"][0]
else:
	job_ids = "0000,0009"
	
		
print "Content-type: text/html"
print "Cache-Control: max-age=10"
print

print '''
<html>
<head>
	<title>gstlal CBC</title>
	<link rel="stylesheet" type="text/css" href="../gstlal.css">
	<script type="text/javascript">var refresh=%f; var longrefresh=%f;</script>
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script type="text/javascript" src="../jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="../gstlal.js"></script>
	<script type="text/javascript">
	google.charts.load('current', {'packages':['corechart', 'table', 'gauge']});
''' % (refresh, longrefresh)

print "	google.charts.setOnLoadCallback(function(){ drawLatencyStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
#print "	google.charts.setOnLoadCallback(function(){ drawLatencyHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
#print "	google.charts.setOnLoadCallback(function(){ drawLatencyGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print ""
print "	google.charts.setOnLoadCallback(function(){ drawSNRStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawSNRHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawLikelihoodStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawLikelihoodHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawFARStatusByNodes(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawFARHistory(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print ""
print "	google.charts.setOnLoadCallback(function(){ drawHorizon(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawVT(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawNoise(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawPSD(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
#print "	google.charts.setOnLoadCallback(function(){ drawNoiseGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
#print "	google.charts.setOnLoadCallback(function(){ drawRangeGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawUpTime(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
#print "	google.charts.setOnLoadCallback(function(){ drawUpTimeGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawDroppedData(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawRAMStatus(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawTimeSinceLast(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawTimeSinceTrigger(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)

print '''
	</script>
</head>

<body>
	<form>
		<ul class="tab">
			<li><img style="margin-left:-40px; margin-top:5px; width:100" src="../gstlal.png"></li>
			<li><a href="#summary" class="tablinks" onclick="openGstlalTab(event, 'Summary')">Results</a></li>
			<li><a href="#status" class="tablinks" onclick="openGstlalTab(event, 'Status', time_since_last_wrapper, latency_status_by_nodes_wrapper, time_since_trigger_wrapper, up_time_wrapper, dropped_wrapper, ram_status_wrapper)">Status</a></li>
			<li><a href="#sens" class="tablinks" onclick="openGstlalTab(event, 'Data', horizon_wrapper, psd_wrapper, noise_wrapper, vt_wrapper)">Data</a></li>
			<li><a href="#snr" class="tablinks" onclick="openGstlalTab(event, 'SNR', snr_status_by_nodes_wrapper, snr_history_wrapper, likelihood_status_by_nodes_wrapper, likelihood_history_wrapper, far_status_by_nodes_wrapper, far_history_wrapper, noise_wrapper_2)">Triggers</a></li>
			<li><a href="#shifts" class="tablinks" onclick="openGstlalTab(event, 'Shifts')">Shifts</a></li>
			<li><a href="#doc" class="tablinks" onclick="openGstlalTab(event, 'About')">About</a></li>
			<li><a href="#offline" class="tablinks" onclick="openGstlalTab(event, 'Offline')">Offline Schedule</a></li>
			<li><a href="#detchar" class="tablinks" onclick="openGstlalTab(event, 'Detchar')">Detchar</a></li>
			<li><a href="#logs" class="tablinks" onclick="openGstlalTab(event, 'Logs')">Logs</a></li>
			<li>
'''				
print '			<input type="text" name="GPS" value="%s" size=8 ><input type="submit" value="GPS" >' % (gps,)
print '			<input type="text" name="Duration" value="%s" size=4 >' % (duration,)
print '			<input type="submit" value="Duration" >'
print '''			
			</li>
			<div id="clock" style="padding-top: 15px; text-align: right;"></div>
		</ul>
	</form>

	<div id="Logs" class="tabcontent">
		<table width=100% height=100%>
			<tr><td><iframe src="https://alog.ligo-wa.caltech.edu/aLOG/iframeSrc.php?authExpired=&content=1&step=&callRep=&startPage=&preview=&printCall=&callUser=&addCommentTo=&callHelp=&callFileType=#&reportSection=8&reportTask=General" width=100% height=100%></iframe></td>
			<td><iframe src="https://alog.ligo-la.caltech.edu/aLOG/iframeSrc.php?authExpired=&content=1&step=&callRep=&startPage=&preview=&printCall=&callUser=&addCommentTo=&callHelp=&callFileType=#&reportSection=6&reportTask=General" width=100% height=100%></iframe></td></tr>
		</table>
	</div>

	<div id="Detchar" class="tabcontent">
'''

if gps =="-1":
	print '''		<iframe src="https://ldas-jobs.ligo.caltech.edu/~detchar/summary/" width=100% height=100%></iframe>'''
else: 
	date = "%04d%02d%02d" % time.gmtime(int(gps)+ 315964785)[0:3]
	print '''		<iframe src="https://ldas-jobs.ligo.caltech.edu/~detchar/summary/day/%s/" width=100%% height=100%%></iframe>''' % (date,)

print '''
	</div>

	<div id="Data" class="tabcontent">
		<div class=gchart id="horizon_wrapper"></div><br>
		<div class=gchart id="vt_wrapper"></div><br>
		<div class=gchart id="psd_wrapper"></div><br>
		<div id="noise_wrapper"></div><br>
		<!-- <div id="noise_table_wrapper"></div> -->
	</div>

	<div id="SNR" class="tabcontent">
		<div class=gchart id="snr_status_by_nodes_wrapper"></div><br>
		<div id="noise_wrapper_2"></div><br>
		<div class=gchart id="snr_history_wrapper"></div><br>
		<div class=gchart id="likelihood_status_by_nodes_wrapper"></div><br>
		<div class=gchart id="likelihood_history_wrapper"></div><br>
		<div class=gchart id="far_status_by_nodes_wrapper"></div><br>
		<div class=gchart id="far_history_wrapper"></div>
	</div>

	<div id="Status" class="tabcontent">
		<div class=gchart id="time_since_last_wrapper"></div><br>
		<div class=gchart id="latency_status_by_nodes_wrapper"></div><br>
		<div class=gchart id="time_since_trigger_wrapper"></div><br>
		<div class=gchart id="up_time_wrapper"></div><br>
		<div class=gchart id="dropped_wrapper"></div><br>
		<div class=gchart id="ram_status_wrapper"></div><br>
		<div><iframe style="background-color:#ecf0f1;" width=100% height=1000 src="https://ldas-jobs.ligo.caltech.edu/~patrick.brockill/llstatus-gstlal/index_auto_reload.html"></iframe></div>
	</div>

	<div id="Summary" class="tabcontent">
		<iframe src="https://ldas-jobs.ligo.caltech.edu/~gstlalcbc/observing/2/" width=100% height=100%></iframe>
	</div>

	<div id="About" class="tabcontent">
		<iframe width=100% height=100% src="https://docs.google.com/document/d/12wJjCz8L1UczqRm86q3-EFnpnIZ2FHPSwKR_kym2L5g/pub?embedded=true"></iframe>
	</div>

	<div id="Shifts" class="tabcontent">
		<iframe src="https://calendar.google.com/calendar/embed?src=ligo.org_070l9orc9lisqgcf2q1arp1ig0%40group.calendar.google.com&ctz=America/New_York" style="border: 0" width=100% height=100% frameborder="0" scrolling="no"></iframe>
	</div>

	<div id="Offline" class="tabcontent">
		<iframe width=100% height=100% src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR1XwazhZYoVbMXFZCq_s2rlzyNwcF0xC4kyhnKrCeXFSWte-2jRodL590RU3PsoX4OVypYyAZ7Nl_8/pubhtml?widget=true&amp;headers=false"></iframe>
	</div>
</body>
</html>
'''
