#!/usr/bin/python

import os,sys
import cgi
import cgitb
cgitb.enable()
form = cgi.parse()

gps = duration = -1
if "GPS" in form:
	gps = form["GPS"][0]
if "duration" in form:
	duration = form["Duration"][0]

print "Content-type: text/html"
print "Cache-Control: max-age=10"
print

print '''
<html>
<head>
	<title>gstlal CBC Latency</title>
	<link rel="stylesheet" type="text/css" href="../gstlal.css">
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script type="text/javascript" src="../jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="../gstlal.js"></script>
	<script type="text/javascript">
	google.charts.load('current', {'packages':['corechart']});
'''
print "		google.charts.setOnLoadCallback(function(){ drawLatencyStatusByNodes(%s,%s) });" % (gps, duration)
print " 	google.charts.setOnLoadCallback(function(){ drawLatencyHistory(%s,%s) });" % (gps, duration)
print " 	google.charts.setOnLoadCallback(function(){ drawLatencyGauge(%s,%s) });" % (gps, duration)
print " "
print "		google.charts.setOnLoadCallback(function(){ drawSNRStatusByNodes(%s,%s) });" % (gps, duration)
print " 	google.charts.setOnLoadCallback(function(){ drawSNRHistory(%s,%s) });" % (gps, duration)
print " "
print " 	google.charts.setOnLoadCallback(function(){ drawHorizon(%s,%s) });" % (gps, duration)
print " 	google.charts.setOnLoadCallback(function(){ drawNoise(%s,%s) });" % (gps, duration)
print " 	google.charts.setOnLoadCallback(function(){ drawPSD(%s,%s) });" % (gps, duration)
print " 	google.charts.setOnLoadCallback(function(){ drawNoiseGauge(%s,%s) });" % (gps, duration)
print " 	google.charts.setOnLoadCallback(function(){ drawRangeGauge(%s,%s) });" % (gps, duration)

print '''
	</script>
</head>

<body>
	<form>
	<div class=topbox> 
		<ul class="tab">
			<li><img width=100px src="http://www.lsc-group.phys.uwm.edu/cgit/gstlal/plain/gstlal/doc/gstlal.png"></li>
			<!-- <li><a href="#ldg" class="tablinks" onclick="openGstlalTab(event, 'LDG')">LDG</a></li> -->
			<li><a href="#dashboard" class="tablinks" onclick="openGstlalTab(event, 'Dashboard')">Dashboard</a></li>
			<!-- <li><a href="#events" class="tablinks" onclick="openGstlalTab(event, 'Events')">Events</a></li> -->
			<li><a href="#detchar" class="tablinks" onclick="openGstlalTab(event, 'Detchar')">Detchar</a></li>
			<li><a href="#logs" class="tablinks" onclick="openGstlalTab(event, 'Logs')">Logs</a></li>
			<li><a href="#noise" class="tablinks" onclick="openGstlalTab(event, 'Noise')">Noise</a></li>
			<li><a href="#sens" class="tablinks" onclick="openGstlalTab(event, 'Sensitivity')">Sensitivity</a></li>
			<li><a href="#latency" class="tablinks" onclick="openGstlalTab(event, 'Latency')">Latency</a></li>
			<li><a href="#snr" class="tablinks" onclick="openGstlalTab(event, 'SNR')">SNR</a></li>
			<li>
				<input type="text" name="GPS" value="" size=11><input type="submit" value="GPS">
				<input type="text" name="Duration" value="" size=7>
				<input type="submit" value="Duration">
			</li>
			<li><div id="clock"></div></li>
		</ul>
	</div>
	</form>

	<br>

	<!--
	<div id="LDG" class="tabcontent">
		<iframe src="https://monitor.ligo.org/gwstatus" width=100% height=675></iframe>
	</div>
	-->

	<div id="Dashboard" class="tabcontent">
		<div id="noise_gauge"></div>
		<div id="range_gauge"></div>
		<div id="latency_gauge_wrapper"></div>
	</div>

	<div id="Logs" class="tabcontent">
		<table width=100%>
			<tr><td><iframe src="https://alog.ligo-wa.caltech.edu/aLOG/iframeSrc.php?authExpired=&content=1&step=&callRep=&startPage=&preview=&printCall=&callUser=&addCommentTo=&callHelp=&callFileType=#&reportSection=8&reportTask=General" width=100% height=675></iframe></td>
			<td><iframe src="https://alog.ligo-la.caltech.edu/aLOG/iframeSrc.php?authExpired=&content=1&step=&callRep=&startPage=&preview=&printCall=&callUser=&addCommentTo=&callHelp=&callFileType=#&reportSection=6&reportTask=General" width=100% height=675></iframe></td></tr>
		</table>
	</div>

	<div id="Detchar" class="tabcontent">
		<iframe src="https://ldas-jobs.ligo.caltech.edu/~detchar/summary/" width=100% height=675></iframe>
	</div>

	<!--
	<div id="Events" class="tabcontent">
		<iframe src="https://gracedb.ligo.org/latest/?query=gstlal" width=100% height=675></iframe>
	</div>
	-->

	<div id="Noise" class="tabcontent">
		<div id="noise"></div>
	</div>

	<div id="Sensitivity" class="tabcontent">
		<div id="horizon"></div>
		<div id="psd"></div>
	</div>

	<div id="Latency" class="tabcontent">
		<div id="latency_status_by_nodes_wrapper"></div>
		<div id="latency_history_wrapper"></div>
	</div>

	<div id="SNR" class="tabcontent">
		<div id="snr_status_by_nodes_wrapper"></div>
		<div id="snr_history_wrapper"></div>
	</div>
</body>
</html>
'''
