#!/usr/bin/python

import os,sys
import cgi
import cgitb
cgitb.enable()
form = cgi.parse()
import time

if "GPS" in form:
	gps = form["GPS"][0]
	refresh =     1000000
	longrefresh = 1000000
else:
	gps = "-1"
	refresh = 5
	longrefresh = 30

if "Duration" in form:
	duration = form["Duration"][0]
else:
	duration = "600"

if "dir" in form:
	analysis_path = form["dir"][0]
else:
	analysis_path = "/home/gstlalcbctest/engineering/10/S6/bns"

if "id" in form:
	job_ids = form["id"][0]
else:
	job_ids = "0000,0009"
	
		
print "Content-type: text/html"
print "Cache-Control: max-age=10"
print

print '''
<html>
<head>
	<title>gstlal CBC Latency</title>
	<link rel="stylesheet" type="text/css" href="../gstlal.css">
	<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
	<script type="text/javascript" src="../jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="../gstlal.js"></script>
	<script type="text/javascript">
	google.charts.load('current', {'packages':['corechart', 'table', 'gauge']});
'''

print "	google.charts.setOnLoadCallback(function(){ drawLatencyGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)
print ""
print "	google.charts.setOnLoadCallback(function(){ drawNoiseGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawRangeGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, refresh, analysis_path, job_ids)
print "	google.charts.setOnLoadCallback(function(){ drawUpTimeGauge(%s,%s,%d,'%s','%s') });" % (gps, duration, longrefresh, analysis_path, job_ids)

print '''
	</script>
</head>

<body>
	<div id="Dashboard">
		<div id="range_gauge_wrapper"></div>
		<div id="noise_gauge_wrapper"></div>
		<table><tr>	<td><div id="uptime_gauge_wrapper"></div></td>
				<td><div id="latency_gauge_wrapper"></div></td>
		</tr></table>
	</div>
<body>
</html>
'''
