# condor commands
# Set the accounting tag from https://ldas-gridmon.ligo.caltech.edu/ldg_accounting/user
ACCOUNTING_TAG=ligo.prod.o1.cbc.bbh.gstlaloffline
GROUP_USER=duncan.meacher
CONDOR_COMMANDS:=--condor-command=accounting_group=$(ACCOUNTING_TAG) --condor-command=accounting_group_user=$(GROUP_USER) --condor-command='Requirements=TARGET.cpuinfo_model=?="60"'

#
# Template bank parameters
#

# The filtering start frequency
LOW_FREQUENCY_CUTOFF = 30.0
# The maximum frequency to filter to
HIGH_FREQUENCY_CUTOFF = 1024.0
# Controls the number of templates in each SVD sub bank
NUM_SPLIT_TEMPLATES = 200
# Number of bins of chi to uniformly bin templates into
NUM_CHI_BINS = 20
# Controls the overlap from sub bank to sub bank - helps mitigate edge effects
# in the SVD.  Redundant templates will be removed
OVERLAP = 30
BANKORIGIN = /home/tito/er8/bank/H1L1-UBERBANK_MAXM100_NS0p05_ER8HMPSD-1126033217-223200.xml.gz
# The location of the original full bank is on Atlas: /home/tito/er8/bank/H1L1-UBERBANK_MAXM100_NS0p05_ER8HMPSD-1126033217-223200.xml.gz
MCHIRP_SPLIT = 1.73
# The approximant that you wish to filter with for BANK_MCHIRP1 and BANK_MCHIRP2, respectively.
APPROXIMANT1 = 0.00:$(MCHIRP_SPLIT):TaylorF2
APPROXIMANT2 = $(MCHIRP_SPLIT):1000.0:SEOBNRv2_ROM_DoubleSpin

#
# Triggering parameters
#

# The detectors to analyze
IFOS = H1 L1 
# The GPS start time for analysis3 (O1C)
START = 1129383017
# The GPS end time for analysis3 (O1C)
STOP = 1133173817
# A user tag for the run
TAG = vt_sensitivity_runs
# A web directory for output
WEBDIR = ~/WWW/LSC/MDC/VT_sensitivity/$(TAG)/$(START)-$(STOP)-chunk456-BBH-C02-run1
# The number of sub banks to process in parallel for each gstlal_inspiral job
NUMBANKS = 5
# The control peak time for the composite detection statistic.  If set to 0 the
# statistic is disabled
PEAK = 0
# The length of autocorrelation chi-squared in sample points
AC_LENGTH = 351
# The minimum number of samples to include in a given time slice
SAMPLES_MIN = 512
# The maximum number of samples to include in the 256 Hz or above time slices
SAMPLES_MAX_256 = 512

#
# additional options, e.g.,
#

#ADDITIONAL_DAG_OPTIONS = "--samples-min $(SAMPLES_MIN) --samples-max-256 $(SAMPLES_MAX_256) --blind-injections BNS-MDC1-WIDE.xml"
ADDITIONAL_DAG_OPTIONS:=--samples-min $(SAMPLES_MIN) --samples-max-256 $(SAMPLES_MAX_256)

#
# Injections
#

# The seed is the string before the suffix _injections.xml
# Change as appropriate, whitespace is important
# This injection file obtained from /home/gstlalcbc/observing/1/offline/er8b-test/HL-INJECTIONS_78901_BBH1-1123858817-3661199.xml
#INJECTIONS := U_dVdzo1pz_GW150914_456789_v1.xml.gz U_dVdzo1pz_GW151226_123456789_v1.xml.gz U_dVdzo1pz_LVT151012_456789_v1.xml.gz U_dVdzo1pz_imf_injections_456789_v1.xml.gz U_dVdzo1pz_lnm_injections_456789_v1.xml.gz
INJECTIONS := U_dVdzo1pz_GW150914_456789_v1.xml.gz U_dVdzo1pz_GW151226_123456789_v2.xml.gz U_dVdzo1pz_LVT151012_456789_v1.xml.gz U_dVdzo1pz_imf_injections_456789_v1.xml.gz U_dVdzo1pz_lnm_injections_456789_v1.xml.gz

# GSTLAL_SEGMENTS Options
SEG_SERVER=https://segments.ligo.org
LIGO_SEGMENTS="$*:DCS-ANALYSIS_READY_C02:1"
SEGMENT_TRIM = 16
SEGMENT_MIN_LENGTH = 512

#GSTLAL VETO Options

# Vetoes file names
# Obtain veto definer from here: https://code.pycbc.phy.syr.edu/detchar/veto-definitions/tree/master/cbc/ER8
#VETODEF = H1L1-HOFT_C00_ER8B_CBC.xml
# Drawn from https://code.pycbc.phy.syr.edu/detchar/veto-definitions/raw/c7062f186d0f630a42e3034be14a437ccf2babf5/cbc/ER8/H1L1-CBC_VETO_DEFINER_C01_16DAY_1126051217-3331800.xml on 12/21/15
VETODEF = H1L1-CBC_VETO_DEFINER_C02_O1_1126051217-11203200.xml
vetoes_suffix := _vetoes.xml
VETOES_FILES  := $(addsuffix $(vetoes_suffix),$(IFOS))

LIGO_VETOES="$*:DMT-INJECTION"

#
# Segment and frame type info
#

# The LIGO frame types
HANFORD_FRAME_TYPE='H1_HOFT_C02'
LIVINGSTON_FRAME_TYPE='L1_HOFT_C02'

# The Channel names. FIXME sadly you have to change the CHANNEL_NAMES string if
# you want to analyze a different set of IFOS
H1_CHANNEL=DCS-CALIB_STRAIN_C02
L1_CHANNEL=DCS-CALIB_STRAIN_C02
CHANNEL_NAMES:=--channel-name=H1=$(H1_CHANNEL) --channel-name=L1=$(L1_CHANNEL)

#
# Get some basic definitions.  NOTE this comes from the share directory probably.
#

include Makefile.offline_analysis_rules

#
# Workflow
#

all : dag

$(INJECTIONS):
	#gsiscp pcdev1.phys.uwm.edu:/home/gstlalcbc/observing/1/offline/er8b-test/$@ ./

BANK = $(notdir $(BANKORIGIN))
$(BANK):
	gsiscp atlas2.atlas.aei.uni-hannover.de:/home/tito/er8/bank/H1L1-UBERBANK_MAXM100_NS0p05_ER8HMPSD-1126033217-223200.xml.gz $@
%_split_bank.cache : $(BANK)
	mkdir -p $*_split_bank
	gstlal_bank_splitter --f-low $(LOW_FREQUENCY_CUTOFF) --group-by-chi $(NUM_CHI_BINS) --output-path $*_split_bank --approximant $(APPROXIMANT1) --approximant $(APPROXIMANT2) --output-cache $@ --overlap $(OVERLAP) --instrument $* --n $(NUM_SPLIT_TEMPLATES) --sort-by mchirp --max-f-final $(HIGH_FREQUENCY_CUTOFF) $(BANK)

plots :
	mkdir plots

$(WEBDIR) : $(MAKEFILE_LIST)
	mkdir -p $(WEBDIR)/OPEN-BOX
	cp $(MAKEFILE_LIST) $@

tisi.xml :
	ligolw_tisi --instrument=H1=0:0:0 --instrument=H2=0:0:0 --instrument=L1=0:0:0 tisi0.xml
	ligolw_tisi --instrument=H1=0:0:0 --instrument=H2=0:0:0 --instrument=L1=25.13274:25.13274:25.13274 tisi1.xml
	ligolw_add --output $@ tisi0.xml tisi1.xml

dag : segments.xml.gz vetoes.xml.gz frame.cache tisi.xml plots $(WEBDIR) $(INJECTIONS) $(BANK_CACHE_FILES)
	gstlal_inspiral_pipe --data-source frames --gps-start-time $(START) --gps-end-time $(STOP) --frame-cache frame.cache --frame-segments-file segments.xml.gz --vetoes vetoes.xml.gz --frame-segments-name datasegments  --control-peak-time $(PEAK) --num-banks $(NUMBANKS) --fir-stride 1 --web-dir $(WEBDIR) --time-slide-file tisi.xml $(INJECTION_LIST) --bank-cache $(BANK_CACHE_STRING) --tolerance 0.9999 --overlap $(OVERLAP) --flow $(LOW_FREQUENCY_CUTOFF) $(CHANNEL_NAMES) --autocorrelation-length $(AC_LENGTH) --ht-gate-threshold 50 $(ADDITIONAL_DAG_OPTIONS) $(CONDOR_COMMANDS) --singles-threshold 6.0 --request-cpu 2 --request-memory 7GB
	sed -i '1s/^/JOBSTATE_LOG logs\/trigger_pipe.jobstate.log\n/' trigger_pipe.dag

H1_frame.cache:
	# FIXME force the observatory column to actually be instrument
	gw_data_find -o H -t $(HANFORD_FRAME_TYPE) -l  -s $(START) -e $(STOP) --url-type file | awk '{ print $$1" $*_"$$2" "$$3" "$$4" "$$5}' > $@

L1_frame.cache:
	# FIXME force the observatory column to actually be instrument
	gw_data_find -o L -t $(LIVINGSTON_FRAME_TYPE) -l  -s $(START) -e $(STOP) --url-type file | awk '{ print $$1" $*_"$$2" "$$3" "$$4" "$$5}' > $@

frame.cache: $(FRAME_CACHE_FILES)
	cat $(FRAME_CACHE_FILES) > frame.cache
	#FIXME: since these frame types were made incorrectly, make sure ligolw_path_to_cache
	#       reads ifo names properly
	sed -i s/H\ $(LIGO_FRAME_TYPE)/H\ H1_$(LIGO_FRAME_TYPE)/g frame.cache
	sed -i s/L\ $(LIGO_FRAME_TYPE)/L\ L1_$(LIGO_FRAME_TYPE)/g frame.cache

%_segmentspadded.xml:
	ligolw_segment_query_dqsegdb --segment-url=${SEG_SERVER} -q --gps-start-time ${START} --gps-end-time ${STOP} --include-segments=$(LIGO_SEGMENTS) --result-name=datasegments > $@

segments.xml.gz: $(SEGMENTS_FILES) frame.cache
	# These segments come from the MDC set	
	ligolw_add --output segdb.xml $(SEGMENTS_FILES)
	ligolw_cut --delete-column segment:segment_def_cdb --delete-column segment:creator_db --delete-column segment_definer:insertion_time segdb.xml
	gstlal_cache_to_segments frame.cache nogaps.xml
	gstlal_segments_operations --segment-file1 segdb.xml --segment-file2 nogaps.xml --intersection --output-file $@
	gstlal_segments_trim --trim $(SEGMENT_TRIM) --gps-start-time $(START) --gps-end-time $(STOP) --min-length $(SEGMENT_MIN_LENGTH) --output $@ $@

#$(VETODEF):
	#gsiscp pcdev1.phys.uwm.edu:/home/scaudill/Projects/uberbank/veto_definers/ER8B/H1L1-HOFT_C00_ER8B_CBC.xml $@

%_vetoes.xml: $(VETODEF)
	ligolw_segments_from_cats_dqsegdb --segment-url=$(SEG_SERVER) --veto-file=$(VETODEF) --gps-start-time $(START) --gps-end-time $(STOP) --cumulative-categories
	gstlal_segments_operations --union --segment-file1 $*-VETOTIME_CAT3-*.xml --segment-name1 VETO_CAT3_CUMULATIVE --segment-file2 $*-VETOTIME_CAT3-*.xml --segment-name2 VETO_CAT3_CUMULATIVE  --output-file $@ --output-segment-name vetoes

vetoes.xml.gz: $(VETOES_FILES)
	ligolw_add --output $@ $(VETOES_FILES)
	ligolw_cut --delete-column segment:segment_def_cdb --delete-column segment:creator_db --delete-column segment_definer:insertion_time $@
	gzip $@


clean:
	-rm -rvf *.sub *.dag* *.cache *.sh logs *.sqlite plots *.html Images *.css *.js
	-rm -rvf lalapps_run_sqlite/ ligolw_* gstlal_*
	-rm -vf segments.xml.gz tisi.xml H1-*.xml H1_*.xml L1-*.xml L1_*xml V1-*.xml V1_*xml ?_injections.xml ????-*_split_bank-*.xml vetoes.xml.gz
	-rm -vf *marginalized*.xml.gz *-ALL_LLOID*.xml.gz
	-rm -vf tisi0.xml tisi1.xml
	-rm -rf *_split_bank*
	-rm -rf nogaps.xml segdb.xml
	-rm -rf bank_aligned_spin.xml.gz
