#!/usr/bin/env python
"""
Generate a LAL frame cache by traversing a directory recursively and looking for all .gwf files.
"""

import os
import os.path
from optparse import OptionParser, Option

opts, args = OptionParser(description=__doc__, usage="%prog [directory]").parse_args()

if len(args) == 1:
	top = args[0]
elif len(args) == 0:
	top = '.'
else:
	raise ValueError("Expected one or zero input arguments, but got %d.", len(opts.args))

for root, dirs, files in os.walk(top):
	for file in files:
		stem, suffix = os.path.splitext(file)
		if suffix == '.gwf':
			observatory, frameType, startTime, duration = stem.split('-')
			ifo, subFrameType = frameType.split('_', 2)
			path = os.path.join(root, file)
			print ifo, frameType, startTime, duration, path
