#!/usr/bin/python
import sys
import cgi
import cgitb
import os
os.environ["MPLCONFIGDIR"] = "/tmp"
import matplotlib
matplotlib.use('Agg')
import numpy
# FIXME don't import this when it is "real"
from numpy import random
import matplotlib.pyplot as plt
cgitb.enable()
form = cgi.FieldStorage()

def plot(dir, dataurl, idrange, datatype = "last", xlabel = "", ylabel = "", title = ""):
	fig = plt.figure(figsize=(25,4.5),)
	fig.patch.set_alpha(0.0)
	h = fig.add_subplot(111, axisbg = 'k')
	plt.subplots_adjust(left = .02, right = 0.98)

	data = []
	ids = ['%04d' % (job,) for job in range(idrange[0], idrange[1]+2)]

	for id in ids:
		url = '%s/%s%s' % (dir, id, dataurl)
		# FIXME relies on 4 digit id
		try:
			tmp = numpy.loadtxt(url)
			if datatype == "last":
				data.append(tmp[-1,1])
			if datatype == "max":
				data.append(tmp[:,1].max())
		except IOError:
			data.append(-1)

	# first plot the missing data
	data = numpy.array(data)
	maxdata = data.max()
	x = [i for i,d in enumerate(data) if d == -1]
	badvalue = -0.05 * maxdata
	baddata = [badvalue for d in data if d == -1]
	h.bar(x, baddata, color='r', alpha=0.9, linewidth=2)
	# then the regular data
	data[data ==  -1] = 0
	x = numpy.arange(len(data))
	h.bar(x, data, color='w', alpha=0.75, linewidth=2)
	plt.xticks(x+.3, ids, rotation=90)
	plt.ylabel(ylabel, fontsize = 18)
	plt.ylim([badvalue, maxdata])
	plt.xlim([x[0], x[-1]])
	if title:
		plt.title(title, fontsize=18)
	plt.savefig(sys.stdout, format="svg")


if "dir" not in form:
	raise ValueError("must specify dir")
if "id" not in form:
	raise ValueError("must specify id")

idrange = [int(n) for n in form.getvalue("id").split(",")]

print >>sys.stdout, 'Cache-Control: no-cache, must-revalidate'
print >>sys.stdout, 'Expires: Mon, 26 Jul 1997 05:00:00 GMT'
print >>sys.stdout, 'Content-type: text/html\r\n'

print """
<html>
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="CACHE-CONTROL" content="NO-CACHE">
</head>
<body bgcolor=#E0E0E0>
<table face="Arial">
<tr>
<td><div id='canvasa'>
"""
plot(form.getvalue("dir"), '_latency_history.txt', idrange, ylabel = "Latency (s)", title = "Latency summary of all jobs, red means data is missing")
print """
</div></td></tr>
<tr><td><div id='canvasb'>
"""
plot(form.getvalue("dir"), '_ram_history.txt', idrange, ylabel = "RAM (GB)", title = "RAM summary of all jobs, red means data is missing")
print """
</div></td></tr>
<tr><td><div id='canvasc'>
"""
plot(form.getvalue("dir"), '_snr_history.txt', idrange, datatype = "max", ylabel = "SNR", title = "max(SNR) of recent triggers summary of all jobs, red means data is missing")
print """
</div></td></tr>
<tr><td><div id='canvasd'>
"""
#plot(baseurl+'_ram_history.txt', "plot", ylabel = "RAM (GB)", xlabel = "Time before now (s)")
print """
</div></td>
</tr>
</table>
"""
print """
</body>
"""

