all: GDS_response_function_bode_plot

FILTERS_FILE = Filters/$(OBSRUN)/GDSFilters/H1GDS_1225558818.npz

GDS_response_function_bode_plot: 
	python ../../../check_calibration/response_function.py --gps-start-time $(SHORT_PLOT_START) --gps-end-time $(SHORT_PLOT_END) --dt 6.103515625e-05 --ifo $(IFO)1 --hoft-frames-cache $(IFO)1_hoft_GDS_no_kappas_frames.cache --raw-frames-cache $(IFO)1_raw_frames.cache --response-file $(FILTERS_FILE) --darm-err-channel-name CAL-DARM_ERR_DBL_DQ


clean: 
	rm *.pdf

