

all:

injections: 
	lalapps_binj  --gps-end-time=10000 --gps-start-time=100 --max-bandwidth=100 --min-bandwidth=10 --max-duration=0.05 --min-duration=0.005 --max-frequency=1000 --min-frequency=40 --max-hrss=10e-19 --min-hrss=10e-22 --output=sine_gauss_inj.xml --population="all_sky_sinegaussian" --time-step=10
