injections: 
	lalapps_binj  --gps-end-time=10000 --gps-start-time=100  --max-frequency=1000 --min-frequency=40 --max-hrss=10e-19 --min-hrss=10e-22 --output=burst_test_inj --population="all_sky_sinegaussian" --time-step=10
