#!/usr/bin/python
import sys

import pygtk
pygtk.require("2.0")
import gobject
gobject.threads_init()
import pygst
pygst.require('0.10')
import gst

from gstlal import pipeparts
from gstlal import simplehandler
import test_common
import numpy

in_rate = 512
out_rate = 2048

opt = sys.argv[1]

gobject.threads_init()
mainloop = gobject.MainLoop()
pipeline = gst.Pipeline("gstlal_play_frames")
handler = simplehandler.Handler(mainloop, pipeline)

head = test_common.test_src(pipeline, buffer_length = 10.0, rate = in_rate, width = 32, channels = 1, test_duration = 10000.0, wave = 5, freq = 0, is_live = False, verbose = True)
head = pipeparts.mkfirbank(pipeline, head, fir_matrix = numpy.ones((200,1)))
if opt == "resample":
	head = pipeparts.mkcapsfilter(pipeline, pipeparts.mkresample(pipeline, head, quality=1), "audio/x-raw-float, rate=%d" % out_rate)
if opt == "interp":
	head = pipeparts.mkcapsfilter(pipeline, pipeparts.mkinterpolator(pipeline, head), "audio/x-raw-float, rate=%d" % out_rate)
pipeparts.mkfakesink(pipeline, head)

# run
if pipeline.set_state(gst.STATE_PLAYING) == gst.STATE_CHANGE_FAILURE:
	raise RuntimeError("pipeline failed to enter PLAYING state")
mainloop.run()

