#Livingston: 
START = 1183905388
END = 1183906844
FILTER_C00 = L1GDS_1175954418.npz
FILTER_C01 = L1DCS_highpass_1175961600.npz
IFO = L

#Hanford: 
#START = 1186200018
#END = 1186201218
#FILTER_C00 = H1GDS_1175954418.npz
#FILTER_C01 = H1DCS_highpass_1173225472.npz
#IFO = H

#Note: Make sure that there is no space after the L or H! 
#Another note: Livingston cluster cannot run this for IFO = H. Make sure that the cluster you're using has the raw frames you want. 

PLOT_START = $(shell echo $(START) + 408 | bc)
PLOT_END = $(shell echo $(END) - 444 | bc)

all: Filters_for_Frames C00_hoft_GDS_frames.cache C01_hoft_GDS_frames.cache response_function_bode_plot

Filters_for_Frames: 
	cp Filters/GDSFilters/$(FILTER_C00) Frames/response_function/C00_no_kappas
	cp Filters/GDSFilters/$(FILTER_C01) Frames/response_function/C01_no_kappas

C00_raw_frames.cache: 
	cd Frames/response_function/C00_no_kappas; gw_data_find -o $(IFO) -t $(IFO)1_R -s $(START) -e $(END) -l --url-type file > $@

C01_raw_frames.cache:
	cd Frames/response_function/C01_no_kappas; gw_data_find -o $(IFO) -t $(IFO)1_R -s $(START) -e $(END) -l --url-type file > $@

C00_hoft_GDS_frames.cache: C00_raw_frames.cache
	cd Frames/response_function/C00_no_kappas; gstlal_compute_strain --data-source frames --frame-cache C00_raw_frames.cache --gps-start-time $(START) --gps-end-time $(END) --frame-duration=4 --frames-per-file=1 --filters-file $(FILTER_C00) --ifo $(IFO)1 --frame-type $(IFO)1_TEST --compression-scheme=6 --compression-level=3 --partial-calibration --control-sample-rate=4096 --no-srcQ --no-fs --wings 400 --no-kappac --no-kappapu --no-kappatst --no-fcc --verbose
	cd Frames/response_function/C00_no_kappas; ls *.gwf | lalapps_path2cache > $@

C01_hoft_GDS_frames.cache: C01_raw_frames.cache
	cd Frames/response_function/C01_no_kappas; gstlal_compute_strain --data-source frames --frame-cache C01_raw_frames.cache --gps-start-time $(START) --gps-end-time $(END) --frame-duration=4 --frames-per-file=1 --filters-file $(FILTER_C01) --ifo $(IFO)1 --frame-type $(IFO)1_TEST --compression-scheme=6 --compression-level=3 --full-calibration --no-srcQ --no-fs --wings 400 --no-kappac --no-kappapu --no-kappatst --no-fcc --verbose
	cd Frames/response_function/C01_no_kappas; ls *.gwf | lalapps_path2cache > $@

response_function_bode_plot: 
	python response_function.py --gps_start_time $(PLOT_START) --gps_end_time $(PLOT_END) --dt 6.103515625e-05 --ifo $(IFO)1 --c00_hoft_frames_cache Frames/response_function/C00_no_kappas/C00_hoft_GDS_frames.cache --c01_hoft_frames_cache Frames/response_function/C01_no_kappas/C01_hoft_GDS_frames.cache --raw_frames_cache Frames/response_function/C01_no_kappas/C01_raw_frames.cache --darm_err_channel_name CAL-DARM_ERR_WHITEN_OUT_DBL_DQ --c00_hoft_channel_name GDS-CALIB_STRAIN --c01_hoft_channel_name GDS-CALIB_STRAIN --calcs_hoft_channel_name CAL-DELTAL_EXTERNAL_DQ --response_file Filters/GDSFilters/$(FILTER_C01) 

clean: 
	rm *.pdf
	cd Frames/response_function/C00_no_kappas; rm *.gwf *.cache
	cd Frames/response_function/C01_no_kappas; rm *.gwf *.cache

