#!/usr/bin/env python
"""
Post process output in order to generate scatter plot and histogram of matches.
"""
__author__ = "Leo Singer <leo.singer@ligo.org>"""


import matplotlib
matplotlib.use('agg')
from matplotlib import ticker
import pylab
import numpy
from glob import glob

data, svd_tolerance = zip(*[(filename, svd_tolerance) for (svd_tolerance, filename) in sorted([(float('.'.join(filename.split('_')[1:3])), 1-numpy.loadtxt(filename)) for filename in glob('match_0_*_0.out')])])

pylab.figure(figsize=(3.25,2))
pylab.subplots_adjust(bottom=0.1, right=0.95)
bp = pylab.boxplot(data, whis=float('inf'), positions=numpy.round(-numpy.log10(1-numpy.array(svd_tolerance))).astype('int'))
for key in ('medians', 'boxes', 'whiskers', 'caps'):
	pylab.setp(bp[key], color='black')
pylab.setp(bp['whiskers'], linestyle='-')
pylab.gca().get_xaxis().set_major_formatter(ticker.FuncFormatter(lambda x, pos: r'%d' % -x))
pylab.yscale('log')
pylab.grid()
#pylab.xlabel(r'$\log_{10}$ (1 - SVD tolerance)')
#pylab.ylabel('mismatch')
pylab.savefig('bw.pdf')
