#!/usr/bin/env python
"""
Post process output in order to generate scatter plot and histogram of matches.
"""
__author__ = "Leo Singer <leo.singer@ligo.org>"""


import matplotlib
matplotlib.use('agg')
import pylab
import numpy
from glob import glob

for (svd_tolerance, filename), color in zip(sorted([(float('.'.join(filename.split('_')[1:3])), filename) for filename in glob('match_0_*_0.out')], reverse=True), 'rgbcm'):
	mismatch = 1 - numpy.loadtxt(filename)
	freqs, bins = numpy.histogram(numpy.log10(mismatch), 20)
	freqs /= numpy.diff(bins)
	bins = 10 ** bins
	pylab.bar(bins[:-1], freqs, numpy.diff(bins), alpha=0.6,  edgecolor = color, facecolor = color, label = 'SVD torance = %g' % svd_tolerance)

pylab.xscale('log')
pylab.grid()
pylab.xlabel('Mismatch between impulse response and nominal template')
pylab.ylabel(r'Logarithmic density (count / log10)')
pylab.title('Mismatch: histogram')
pylab.legend(loc = 'upper right')
pylab.savefig('hist.pdf')
pylab.savefig('hist.png')
